### 2.(a)
### 我們分別使用sample法和ceiling法模擬了1000次的亂數生成，並且分成小區間與大區間，
### 在小區間下，亂數的生成範圍為1~10，大區間下，亂數的生成範圍為1~100

library(ggplot2)

generate_histogram <- function(data, k, title) {
  histogram <- ggplot(data.frame(x = data), aes(x)) +
    geom_histogram(binwidth = 1, fill = "blue", alpha = 0.5) +
    labs(title = title, x = "Value", y = "Frequency")
  print(histogram)
}

calculate_and_test <- function(data, k) {
  num <- c()
  for (i in 0:(k-1)) {
    c <- data[data <= (1*(i+1)) & data > (1*i)]
    num <- c(num, length(c))
  }
  print(num)
  chisq.test(num, p = rep(1/k, k))
}

set.seed(123)
sample_data_10 <- sample(1:10, 1000, replace = TRUE)
ceiling_data_10 <- ceiling(runif(1000) * 10)
sample_data_100 <- sample(1:100, 1000, replace = TRUE)
ceiling_data_100 <- ceiling(runif(1000) * 100)

generate_histogram(sample_data_10, 10, "Random 1~10 Generated by 'sample'")
generate_histogram(ceiling_data_10, 10, "Random 1~10 Generated by 'ceiling(runif)'")
generate_histogram(sample_data_100, 100, "Random 1~100 Generated by 'sample'")
generate_histogram(ceiling_data_100, 100, "Random 1~100 Generated by 'ceiling(runif)'")

calculate_and_test(sample_data_10, 10)
calculate_and_test(ceiling_data_10, 10)
calculate_and_test(sample_data_100, 100)
calculate_and_test(ceiling_data_100, 100)

### 2.(b)
pi_fn<-function(seed,n){
  un<-seed
  a<-c()
  for (i in 1:n){
    un<-(un+pi)^5
    un<-un%%1
    a<-c(a,un)
  }
  return(a)
}

example5_b_big<-pi_fn(100,1000)
example5_b_small<-pi_fn(101,100)


hist(example5_b_small,main="Pi method of n=100")
hist(example5_b_big,main="Pi method of n=1000")

len_vector_b_big<-c()
for( i in 0:9){
  c = example5_b_big[example5_b_big <=(0.1*(i+1)) & example5_b_big > (0.1*i)]
  len_vector_b_big = c(len_vector_b_big,length(c))
}
len_vector_b_big
chisq.test(len_vector_b_big,p = rep(1/10, 10))

len_vector_b_small<-c()
for( i in 0:9){
  c = example5_b_small[example5_b_small <=(0.1*(i+1)) & example5_b_small > (0.1*i)]
  len_vector_b_small = c(len_vector_b_small,length(c))
}
len_vector_b_small
chisq.test(len_vector_b_small,p = rep(1/10, 10))

###.4
gap.test=function(data,a,b){
  n=length(data)
  x=c(1:n)*(a<data & data<b)
  x1=x[x>0]
  y=x1[-1]-x1[-length(x1)]-1
  return(table(y))
}

set.seed(123)
uniform_data <- runif(1200)
gap_counts <- gap.test(uniform_data, 0.2, 0.8)

result_vector <- numeric()
for (i in c(0:5)) {
  a = 0.6*0.4^i
  result_vector <- c(result_vector, a)
}
result_vector[6] <- 1 - sum(result_vector[1:5])
observation <- c(446, 179,  63,  26,  14, 5) 
chisq.test(observation, p = result_vector)

permute.test=function(data,k){
  y=rep(10,k)^c((k-1):0)
  x=matrix(data,ncol=k,byrow=T)
  x1=apply(x,1,rank)
  yy=apply(x1*y,2,sum)
  return(table(yy))
}

permute.test(uniform_data, 3)
observation <- c(54, 66,  67,  80,  65, 68)
chisq.test(observation, p = rep(1/6, 6))

run.test <- function(data, base_number) {
  n <- length(data)
  observed_runs <- sum(data > base_number)
  expected_runs <- n / 2
  p_value <- 2*pbinom(observed_runs, size = n, prob = 0.5, lower.tail = TRUE)
  return(list(observed_runs = observed_runs, expected_runs = expected_runs, p_value = p_value))
}

run.test(uniform_data, 0.5)

### 測試python生產出的亂數
py_data <- read.csv('random_numbers.csv')
py_data <- py_data[, 1]
gap_counts <- gap.test(py_data, 0.2, 0.8)

result_vector <- numeric()
for (i in c(0:5)) {
  a = 0.6*0.4^i
  result_vector <- c(result_vector, a)
}
result_vector[6] <- 1 - sum(result_vector[1:5])
observation <- c(423, 169,  69,  21,  16, 10) 
chisq.test(observation, p = result_vector)

permute.test(py_data, 3)
observation <- c(71, 69,  58,  77,  68, 57)
chisq.test(observation, p = rep(1/6, 6))

run.test(py_data, 0.5)

###.6
lottery_numbers <- c(
  22, 31, 34, 25, 21, 19,
  5, 18, 25, 26, 35, 42,
  32, 21, 9, 27, 31, 6,
  5, 25, 2, 16, 32, 9,
  15, 29, 5, 36, 13, 10,
  36, 16, 12, 26, 8, 34,
  4, 40, 27, 21, 14, 5,
  29, 4, 10, 23, 39, 14,
  30, 12, 40, 32, 35, 20,
  40, 6, 20, 29, 38, 35,
  32, 10, 15, 2, 30, 23,
  24, 20, 36, 19, 7, 12,
  1, 6, 7, 12, 42, 20,
  25, 39, 20, 38, 29, 37,
  26, 2, 15, 29, 4, 33,
  17, 39, 3, 15, 11, 1,
  13, 39, 28, 30, 25, 29,
  7, 9, 29, 34, 39, 36,
  28, 31, 16, 35, 6, 30,
  10, 32, 13, 4, 9, 33)
interval <- cut(lottery_numbers, breaks = seq(0, 42, by = 6))
hist(lottery_numbers, breaks = seq(0, 50, by = 6), main = "Histogram of Lottery Numbers", xlab = "Interval")
chisq.test(table(interval), p = rep(1/7, 7))
set.seed(123) 

sum_groups <- function(numbers, group_size) {
  num_groups <- length(numbers) / group_size
  group_sums <- sapply(1:num_groups, function(i) {
    sum(numbers[((i - 1) * group_size + 1):(i * group_size)])
  })
  return(group_sums)
}

group_sums <- sum_groups(lottery_numbers, 6)
print(group_sums)

dummy_variable_number <- ifelse(group_sums > 129, 1, 0)
first_half <- dummy_variable_number[1:10]
second_half <- dummy_variable_number[11:20]

count_first_0 <- sum(first_half == 0)
count_first_1 <- sum(first_half == 1)
count_second_0 <- sum(second_half == 0)
count_second_1 <- sum(second_half == 1)
matrix_data <- matrix(c(count_first_0, count_second_0, count_first_1, count_second_1), nrow = 2, byrow = TRUE)

print(matrix_data)
chisq.test(matrix_data,correct = FALSE)
